substitutions:
  name: ecodan-heatpump
  friendlyName: Ecodan heatpump
# heatpump heating/cooling switch
# available modes: HEAT_ROOM_TEMP, HEAT_FLOW_TEMP, HEAT_COMPENSATION_CURVE, COOL_ROOM_TEMP, COOL_FLOW_TEMP
  default_heating_switch_mode: HEAT_COMPENSATION_CURVE
  default_cooling_switch_mode: COOL_FLOW_TEMP

esphome:
  name: ${name}
  friendly_name: ${friendlyName}

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  power_save_mode: light
  ap:
    ssid: "${name}"
    password: "configesp"
    ap_timeout: 15s

captive_portal:

ota:
  platform: esphome
#  password: !secret heatpump_ota_password

api:
  reboot_timeout: 0s
#  encryption:
#    key: !secret heatpump_encryption_key

# external_components:
# - source:
#     type: local
#     path: components
#   components: [ ecodan ]

# packages:
#  base: !include confs/base.yaml # 
#  esp32: !include confs/esp32s3.yaml # esp32.yaml for regular board
#  zone1: !include confs/zone1.yaml
# # disable if you don't want to use zone 2
# # zone2: !include confs/zone2.yaml
# # change language labels to -en for English or -nl for Dutch
# # substitutions: !include confs/ecodan-labels-nl.yaml
#  substitutions: !include confs/ecodan-labels-en.yaml
#  svc: !include confs/server-control.yaml
#  dbg: !include confs/debug.yaml

external_components:
  - source: github://gekkekoe/esphome-ecodan-hp@main
    components: [ ecodan ]
    refresh: always

packages:
  remote_package:
    url: https://github.com/gekkekoe/esphome-ecodan-hp/
    ref: main
    refresh: always
    files: [ 
            confs/base.yaml,        # required
            confs/esp32s3.yaml,     # confs/esp32.yaml, for regular board
            confs/zone1.yaml,
            ## enable if you want to use zone 2
            #confs/zone2.yaml,
            ## enable label language file
            confs/ecodan-labels-en.yaml,
            #confs/ecodan-labels-nl.yaml,
            #confs/ecodan-labels-it.yaml,
            #confs/ecodan-labels-fr.yaml,
            confs/server-control.yaml,
            #confs/debug.yaml,
           ]

# enable logger
logger:
  baud_rate: 0
  logs:
    esp32.preferences: DEBUG
    sensor: DEBUG
    text_sensor: DEBUG
    binary_sensor: DEBUG
    switch: DEBUG
    button: DEBUG
    number: DEBUG
    climate: DEBUG
    component: ERROR
    ecodan.component: ERROR

# Enable Web server.
web_server:
  port: 80

ecodan:
  id: ecodan_instance
  rx_pin: GPIO2
  tx_pin: GPIO1
